[package]
name = "xor"
version = "0.1.4"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[dev-dependencies]
expectest = { version = "0.6.0", features = [] }

[dependencies]
rustc-serialize = "0.3"
